import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { marked } from './vendor/marked.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'site');
const config=JSON.parse(fs.readFileSync(path.join(root,'site.config.json'),'utf8'));
const pages=[
 ['research','The project','Research','The question behind RES, why it matters, and what exists today.'],
 ['findings','Current findings','Evidence','Completed experiments, failed gates, and the limits of the current evidence.'],
 ['architecture','Delegation architecture','Architecture','A proposed separation of evidence, review, permission, and action.'],
 ['resources','Research resources','Resources','Public documentation, archived reports, preregistrations, and source records.'],
 ['support','Support RES','Support','Help fund controlled experiments, replication, and public research documentation.'],
 ['paper','The RES framework','Working paper','A falsifiable framework for actor-indexed causal mediation in AI.'],
 ['methods','Methods and reproducibility','Methods','How controls, preregistration, paired analysis, and causal validation limit claims.'],
 ['roadmap','Research roadmap','Next steps','The next experiments justified by the current record.'],
 ['glossary','RES glossary','Glossary','Plain-language definitions for the research and architecture.']
];
const nav=pages.slice(0,5);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const slug=s=>s.toLowerCase().replace(/<[^>]*>/g,'').replace(/[^\p{L}\p{N}\s-]/gu,'').trim().replace(/\s+/g,'-');
const favicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#113f3a"/><text x="32" y="46" text-anchor="middle" font-family="Georgia,serif" font-size="47" fill="#f6faf7">R</text><circle cx="51" cy="14" r="5" fill="#ef926f"/></svg>';
const navLinks=(current)=>nav.map(([id,,label])=>`<a href="${id}.html"${id===current?' aria-current="page"':''}${id==='support'?' class="nav-support"':''}>${label}</a>`).join('');
function shell(title,description,current,body){
 const origin=config.canonicalOrigin.replace(/\/$/,'');
 if(origin && (!/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(origin))) throw Error('canonicalOrigin must be a confirmed HTTPS origin');
 const filename=current==='home'?'':`${current}.html`;
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#113f3a"><title>${esc(title)} | RES</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} | RES"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${origin?`<link rel="canonical" href="${origin}/${filename}"><meta property="og:url" content="${origin}/${filename}">`:''}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${encodeURIComponent(favicon)}"><link rel="stylesheet" href="assets/site.css"></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="RES home"><span class="brand-mark" aria-hidden="true">res</span><span class="brand-name">Relational–<br>Episodic Self</span></a><nav class="desktop-nav" aria-label="Main navigation">${navLinks(current)}</nav><details class="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation">${navLinks(current)}</nav></details></div></header>
${body}
<footer class="site-footer"><div class="wrap"><div class="footer-top"><div><p class="footer-title">The RES project</p><p class="footer-note">Independent research on acting systems, evidence, and human authority.</p><a href="mailto:${esc(config.email)}">${esc(config.email)}</a></div><nav class="footer-links" aria-label="More from RES"><a href="${esc(config.repositoryUrl)}">${esc(config.repositoryLabel)}</a><a href="methods.html">Methods</a><a href="roadmap.html">Roadmap</a><a href="glossary.html">Glossary</a></nav></div><div class="footer-bottom"><span>Research snapshot · 25 September 2026</span><span>Early-stage research · No established model-level RES finding</span></div></div></footer></body></html>\n`;
}
function docPage(id,title,kicker,description){
 const input=fs.readFileSync(path.join(root,'docs',`${id}.md`),'utf8');
 const h1=input.match(/^# (.+)$/m)?.[1]||title;
 const headings=[]; const seen=new Map();
 const renderer=new marked.Renderer();
 renderer.heading=function(token){const content=this.parser.parseInline(token.tokens);const base=slug(token.text);const n=seen.get(base)||0;seen.set(base,n+1);const anchor=n?`${base}-${n}`:base;if(token.depth===2)headings.push({anchor,text:token.text});return `<h${token.depth} id="${anchor}">${content}</h${token.depth}>\n`;};
 let html=marked.parse(input.replace(/^# .+\n+/,'').replace(/\]\((research|findings|architecture|resources|support|paper|methods|roadmap|glossary)\.md([#][^)]*)?\)/g,']($1.html$2)'),{renderer,gfm:true});
 html=html.replaceAll('href="../evidence/','href="downloads/evidence/').replaceAll('<table>','<div class="table-wrap" role="region" aria-label="Research table; scroll horizontally if needed" tabindex="0"><table>').replaceAll('</table>','</table></div>');
 const toc=headings.map(h=>`<li><a href="#${h.anchor}">${esc(h.text)}</a></li>`).join('');
 return shell(title,description,id,`<main id="main"><header class="page-mast"><div class="wrap"><p class="eyebrow">RES / ${esc(kicker)}</p><h1>${esc(h1)}</h1><p class="page-deck">${esc(description)}</p><div class="page-tools"><a href="downloads/${id}.md" download>Download Markdown</a><a href="resources.html#source-snapshot">Source snapshot</a><span>Public research edition</span></div></div></header><div class="wrap reading-layout"><aside class="toc" aria-label="Contents"><details open><summary>On this page</summary><ol>${toc}</ol></details></aside><article class="reading-content">${html}<p class="source-note">RES public research documentation · 25 September 2026. Findings refer to the archived conditions described in the evidence record.</p></article></div></main>`);
}
function home(){return shell('Research for governable AI agents','RES investigates how AI systems track actors, authority, and commitments, and develops testable ideas for accountable delegation.','home',`<main id="main"><section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">Independent AI research</p><h1>Keep human authority inside the loop.</h1><p class="intro">When AI acts on our behalf, it needs to keep track of who is acting, what permission applies, and which commitments matter. RES puts those distinctions to the test.</p><div class="actions"><a class="button button-primary" href="${esc(config.donateUrl)}">Support the research <span aria-hidden="true">↗</span></a><a class="button" href="research.html">Explore RES</a></div><p class="hero-note">Relational–Episodic Self · Research under IFERS fiscal sponsorship</p></div><aside class="question-panel" aria-label="The project's research questions"><p class="eyebrow">The questions that guide us</p><h2>Who is acting.<br>What is allowed.<br>What the evidence says.</h2><div class="question-row"><span>01</span><div><strong>Actor</strong><p>Can a system distinguish its own task and commitments from another agent’s?</p></div></div><div class="question-row"><span>02</span><div><strong>Authority</strong><p>Can permission remain explicit when work is handed off?</p></div></div><div class="question-row"><span>03</span><div><strong>Evidence</strong><p>Can an independent test make our preferred explanation fail?</p></div></div></aside></div></section>
<div class="status-band"><div class="wrap status-grid"><div class="status-item"><span class="status-label">Current phase</span><strong>Replication and assay development</strong></div><div class="status-item"><span class="status-label">Evidence boundary</span><strong>No established model-level RES finding</strong></div><div class="status-item"><span class="status-label">Immediate need</span><strong>Model access and compute</strong></div></div></div>
<section class="section"><div class="wrap"><div class="section-top"><div><p class="eyebrow">Why this work matters</p><h2>Delegation needs<br>accountability.</h2></div><p>Being able to take an action is different from having permission. A persuasive account is different from independent evidence. RES studies these distinctions—and asks how they can survive complex tasks, handoffs, and failures.</p></div><div class="chapter-grid"><article class="chapter"><span class="number">01 / Research</span><h3>Test the acting system.</h3><p>Turn questions about “I,” “we,” and “other” into controlled experiments with rival explanations and explicit failure conditions.</p><a href="paper.html">Read the framework</a></article><article class="chapter"><span class="number">02 / Evidence</span><h3>Publish what holds up.</h3><p>Track successful controls, mixed results, failed gates, and non-replications. Let the evidence set the next question.</p><a href="findings.html">Inspect the findings</a></article><article class="chapter"><span class="number">03 / Architecture</span><h3>Govern the governors.</h3><p>Keep records, audit judgments, permission, and execution separate. Make authority inspectable and actions bounded.</p><a href="architecture.html">Explore the design</a></article></div></div></section>
<section class="section evidence-section"><div class="wrap"><div class="section-top"><div><p class="eyebrow">From the research record</p><h2>A promising result.<br>A necessary retest.</h2></div><p>Changing the wording improved performance in one diagnostic. A fresh five-factor comparison did not replicate the benefit. Both results belong in the public record.</p></div><div class="evidence-grid"><article class="evidence-box"><h3>Initial matched diagnostic</h3><div class="big-result">17/32 → 26/32</div><p>Generated answers: code-mapped versus neutral labels and task wording.</p><p class="meta">+28.125 percentage points · Diagnostic evidence</p></article><article class="evidence-box"><h3>Fresh five-factor comparison</h3><div class="big-result">35/64 · 38/64</div><p>Generated answers: loaded versus fully neutral wording on fresh fixtures.</p><p class="meta">Exact paired p = 0.507812 · Benefit not replicated</p></article></div><p class="evidence-footnote">Different fixtures and comparison conditions. These studies do not form one pooled effect, reverse the original failed gate, or identify a RES mechanism.</p><div class="actions"><a class="button" href="findings.html">Read the results and limits</a></div></div></section>
<section class="section"><div class="wrap"><div class="section-top"><div><p class="eyebrow">Open to scrutiny</p><h2>Follow the reasoning.<br>Check the record.</h2></div><p>Read the public framework, inspect the protocols and archived reports, or help design an independent test. The documentation includes a glossary and a staged research roadmap.</p></div><div class="actions"><a class="button" href="resources.html">Browse research resources</a><a class="button" href="roadmap.html">See what comes next</a></div></div></section>
<section class="section"><div class="wrap support-panel"><div><p class="eyebrow">Fund the next careful test</p><h2>Better evidence takes more than one answer.</h2><p>Contributions support model tokens, API access, compute, and the repeated measurements needed to test alternatives and document failures.</p><div class="actions"><a class="button button-primary" href="${esc(config.donateUrl)}">Donate on GoFundMe <span aria-hidden="true">↗</span></a><a href="support.html">How support helps</a></div></div><aside class="support-details"><h3>Fiscal sponsorship</h3><p>RES operates under an agreement with the Institute for Education, Research, and Scholarships (IFERS).</p><p>Research review, collaboration, compute support, and grant inquiries are welcome.</p><a href="mailto:${esc(config.email)}">${esc(config.email)}</a></aside></div></section></main>`);}

fs.mkdirSync(path.join(out,'assets'),{recursive:true});fs.mkdirSync(path.join(out,'downloads'),{recursive:true});
fs.copyFileSync(path.join(root,'assets/site.css'),path.join(out,'assets/site.css'));
for(const p of pages){fs.writeFileSync(path.join(out,p[0]+'.html'),docPage(...p));fs.copyFileSync(path.join(root,'docs',p[0]+'.md'),path.join(out,'downloads',p[0]+'.md'));}
fs.writeFileSync(path.join(out,'index.html'),home());
fs.writeFileSync(path.join(out,'404.html'),shell('Page not found','Return to the RES project and its research documentation.','404','<main id="main" class="wrap empty-page"><p class="eyebrow">RES / 404</p><h1>This page is not here.</h1><p>The project overview and research index can help you find the material you need.</p><div class="actions"><a class="button button-primary" href="/">Return home</a><a class="button" href="/resources.html">Research resources</a></div></main>').replace('href="assets/site.css"','href="/assets/site.css"').replace(/href="(index|research|findings|architecture|resources|support|methods|roadmap|glossary)\.html"/g,'href="/$1.html"'));
fs.writeFileSync(path.join(out,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src \'none\'; style-src \'self\'; img-src \'self\' data:; font-src \'self\'; base-uri \'none\'; form-action \'none\'; frame-ancestors \'none\'\n');
const origin=config.canonicalOrigin.replace(/\/$/,'');
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\n${origin?`Sitemap: ${origin}/sitemap.xml\n`:''}`);
if(origin)fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...pages.map(p=>p[0]+'.html')].map(p=>`<url><loc>${esc(origin+'/'+p)}</loc><lastmod>${config.updated}</lastmod></url>`).join('')}</urlset>\n`);else if(fs.existsSync(path.join(out,'sitemap.xml')))fs.unlinkSync(path.join(out,'sitemap.xml'));
const evidenceRoot=path.join(root,'evidence');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
for(const file of walk(evidenceRoot)){const rel=path.relative(evidenceRoot,file);const dest=path.join(out,'downloads/evidence',rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(file,dest);}
console.log(`Built ${pages.length+2} HTML pages in site/. No model calls or network dependencies.`);
